var data={
	img1:[
		"./img/img1_1.jpg",
		"SeeYouAgain",
		"img/img1_2.png",
		"我们期待着明年的今天",
		"还能够保存这样无忧的笑脸"
	],
	img2:[
		"./img/img2_1.jpg",
		"./img/img2_2.jpg",
		"./img/img2_3.jpg",
		"./img/img2_4.jpg",
		"./img/img2_5.jpg",
		"./img/img2_6.jpg"
	],
	imgS2:[
		"./img/img2_6.jpg",
		"./img/img1_1.jpg",
		"./img/img2_4.jpg",
		"./img/img2_3.jpg",
		"./img/img2_2.jpg",
		"./img/img2_1.jpg"
	],
	img3:[
		"./img/img3_1.jpg",
		"./img/img3_2.jpg",
		"./img/img3_3.jpg",
		"./img/img3_4.jpg"
	],
	img4:[
		"./img/img4_1.jpg",
		"./img/img4_2.jpg",
		"./img/img4_3.jpg",
	],
	img5:[
		"./img/img5_1.jpg",
		"./img/img5_2.jpg",
		"./img/img5_3.jpg",
		"./img/img5_4.jpg",
		"./img/img5_5.jpg",
		"./img/img5_6.jpg"
	],
	img6:[
		"./img/img6_1.jpg",
		"./img/img6_2.jpg",
		"./img/img6_3.jpg",
		"./img/img6_4.jpg"
	],
	img7:[
		"./img/img7_1.jpg",
		"./img/img7_2.jpg",
		"./img/img7_3.jpg",
		"./img/img7_4.jpg",
		"./img/img7_5.jpg"
	]
}
var textS=["SeeYouAgain"];
